import ArrayWrapper from "components/array/ArrayWrapper";
import Head from "next/head";
import React from "react";

export default function Home({}) {

  return (
    <div className="flex-1 h-screen">
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <ArrayWrapper />
      </main>
    </div>
  );
}
